# Generated by Django 5.2.12 on 2026-03-24 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_fen', models.TextField(default='start')),
                ('turn', models.CharField(default='white', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player_white', models.CharField(blank=True, max_length=255, null=True)),
                ('player_black', models.CharField(blank=True, max_length=255, null=True)),
                ('is_started', models.BooleanField(default=False)),
                ('white_time', models.IntegerField(default=1200)),
                ('black_time', models.IntegerField(default=600)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.IntegerField(default=1200)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_number', models.IntegerField()),
                ('notation', models.CharField(max_length=10)),
                ('time_spent', models.FloatField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='game.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
            ],
        ),
    ]
