# Generated by Django 5.2.12 on 2026-03-24 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='name',
            new_name='nickname',
        ),
        migrations.RemoveField(
            model_name='player',
            name='rating',
        ),
    ]
