# Generated by Django 5.2.12 on 2026-03-24 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_rename_name_player_nickname_remove_player_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='nickname',
            new_name='name',
        ),
    ]
