# Generated by Django 5.2.12 on 2026-03-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_rename_nickname_player_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='last_move_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='white_time',
            field=models.IntegerField(default=600),
        ),
    ]
