# Generated by Django 5.2.12 on 2026-03-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_last_move_time_alter_game_white_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='last_move_time',
            field=models.FloatField(default=0),
        ),
    ]
