# Generated by Django 5.2.12 on 2026-03-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_game_is_finished_game_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='black_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='white_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
