# Generated by Django 5.2.12 on 2026-03-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_game_black_time_alter_game_white_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='black_time',
            field=models.IntegerField(default=600),
        ),
        migrations.AlterField(
            model_name='game',
            name='white_time',
            field=models.IntegerField(default=600),
        ),
    ]
