# Generated by Django 5.2.12 on 2026-03-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_game_black_time_alter_game_white_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='move',
            name='player',
        ),
        migrations.AddField(
            model_name='move',
            name='player_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
