# Generated by Django 5.2.12 on 2026-03-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_remove_move_player_move_player_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player_color',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
