# Generated by Django 5.2.12 on 2026-03-25 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_game_player_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='move',
            old_name='player_id',
            new_name='player_color',
        ),
    ]
