# Generated by Django 5.2.12 on 2026-03-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_rename_player_id_move_player_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='player_color',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
