# Generated by Django 5.2.12 on 2026-03-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_alter_move_player_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='initial_fen',
            field=models.CharField(default='start', max_length=100),
        ),
    ]
